/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiGovernanceFrameworkRouteImport } from './routes/ai-governance-framework'
import { Route as ArRouteImport } from './routes/ar'
import { Route as CsRouteImport } from './routes/cs'
import { Route as ElRouteImport } from './routes/el'
import { Route as EsRouteImport } from './routes/es'
import { Route as FrRouteImport } from './routes/fr'
import { Route as HeRouteImport } from './routes/he'
import { Route as ItRouteImport } from './routes/it'
import { Route as JaRouteImport } from './routes/ja'
import { Route as KoRouteImport } from './routes/ko'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as PtRouteImport } from './routes/pt'
import { Route as RuRouteImport } from './routes/ru'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SvRouteImport } from './routes/sv'
import { Route as SwRouteImport } from './routes/sw'
import { Route as ZhRouteImport } from './routes/zh'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiGovernanceFrameworkRoute = AiGovernanceFrameworkRouteImport.update({
  id: '/ai-governance-framework',
  path: '/ai-governance-framework',
  getParentRoute: () => rootRouteImport,
} as any)
const ArRoute = ArRouteImport.update({
  id: '/ar',
  path: '/ar',
  getParentRoute: () => rootRouteImport,
} as any)
const CsRoute = CsRouteImport.update({
  id: '/cs',
  path: '/cs',
  getParentRoute: () => rootRouteImport,
} as any)
const ElRoute = ElRouteImport.update({
  id: '/el',
  path: '/el',
  getParentRoute: () => rootRouteImport,
} as any)
const EsRoute = EsRouteImport.update({
  id: '/es',
  path: '/es',
  getParentRoute: () => rootRouteImport,
} as any)
const FrRoute = FrRouteImport.update({
  id: '/fr',
  path: '/fr',
  getParentRoute: () => rootRouteImport,
} as any)
const HeRoute = HeRouteImport.update({
  id: '/he',
  path: '/he',
  getParentRoute: () => rootRouteImport,
} as any)
const ItRoute = ItRouteImport.update({
  id: '/it',
  path: '/it',
  getParentRoute: () => rootRouteImport,
} as any)
const JaRoute = JaRouteImport.update({
  id: '/ja',
  path: '/ja',
  getParentRoute: () => rootRouteImport,
} as any)
const KoRoute = KoRouteImport.update({
  id: '/ko',
  path: '/ko',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const PtRoute = PtRouteImport.update({
  id: '/pt',
  path: '/pt',
  getParentRoute: () => rootRouteImport,
} as any)
const RuRoute = RuRouteImport.update({
  id: '/ru',
  path: '/ru',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SvRoute = SvRouteImport.update({
  id: '/sv',
  path: '/sv',
  getParentRoute: () => rootRouteImport,
} as any)
const SwRoute = SwRouteImport.update({
  id: '/sw',
  path: '/sw',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhRoute = ZhRouteImport.update({
  id: '/zh',
  path: '/zh',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-governance-framework': typeof AiGovernanceFrameworkRoute
  '/ar': typeof ArRoute
  '/cs': typeof CsRoute
  '/el': typeof ElRoute
  '/es': typeof EsRoute
  '/fr': typeof FrRoute
  '/he': typeof HeRoute
  '/it': typeof ItRoute
  '/ja': typeof JaRoute
  '/ko': typeof KoRoute
  '/mcp': typeof McpRoute
  '/pt': typeof PtRoute
  '/ru': typeof RuRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sv': typeof SvRoute
  '/sw': typeof SwRoute
  '/zh': typeof ZhRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-governance-framework': typeof AiGovernanceFrameworkRoute
  '/ar': typeof ArRoute
  '/cs': typeof CsRoute
  '/el': typeof ElRoute
  '/es': typeof EsRoute
  '/fr': typeof FrRoute
  '/he': typeof HeRoute
  '/it': typeof ItRoute
  '/ja': typeof JaRoute
  '/ko': typeof KoRoute
  '/mcp': typeof McpRoute
  '/pt': typeof PtRoute
  '/ru': typeof RuRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sv': typeof SvRoute
  '/sw': typeof SwRoute
  '/zh': typeof ZhRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-governance-framework': typeof AiGovernanceFrameworkRoute
  '/ar': typeof ArRoute
  '/cs': typeof CsRoute
  '/el': typeof ElRoute
  '/es': typeof EsRoute
  '/fr': typeof FrRoute
  '/he': typeof HeRoute
  '/it': typeof ItRoute
  '/ja': typeof JaRoute
  '/ko': typeof KoRoute
  '/mcp': typeof McpRoute
  '/pt': typeof PtRoute
  '/ru': typeof RuRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sv': typeof SvRoute
  '/sw': typeof SwRoute
  '/zh': typeof ZhRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-governance-framework'
    | '/ar'
    | '/cs'
    | '/el'
    | '/es'
    | '/fr'
    | '/he'
    | '/it'
    | '/ja'
    | '/ko'
    | '/mcp'
    | '/pt'
    | '/ru'
    | '/sitemap.xml'
    | '/sv'
    | '/sw'
    | '/zh'
    | '/.well-known/oauth-protected-resource'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-governance-framework'
    | '/ar'
    | '/cs'
    | '/el'
    | '/es'
    | '/fr'
    | '/he'
    | '/it'
    | '/ja'
    | '/ko'
    | '/mcp'
    | '/pt'
    | '/ru'
    | '/sitemap.xml'
    | '/sv'
    | '/sw'
    | '/zh'
    | '/.well-known/oauth-protected-resource'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/ai-governance-framework'
    | '/ar'
    | '/cs'
    | '/el'
    | '/es'
    | '/fr'
    | '/he'
    | '/it'
    | '/ja'
    | '/ko'
    | '/mcp'
    | '/pt'
    | '/ru'
    | '/sitemap.xml'
    | '/sv'
    | '/sw'
    | '/zh'
    | '/.well-known/oauth-protected-resource'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiGovernanceFrameworkRoute: typeof AiGovernanceFrameworkRoute
  ArRoute: typeof ArRoute
  CsRoute: typeof CsRoute
  ElRoute: typeof ElRoute
  EsRoute: typeof EsRoute
  FrRoute: typeof FrRoute
  HeRoute: typeof HeRoute
  ItRoute: typeof ItRoute
  JaRoute: typeof JaRoute
  KoRoute: typeof KoRoute
  McpRoute: typeof McpRoute
  PtRoute: typeof PtRoute
  RuRoute: typeof RuRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SvRoute: typeof SvRoute
  SwRoute: typeof SwRoute
  ZhRoute: typeof ZhRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-governance-framework': {
      id: '/ai-governance-framework'
      path: '/ai-governance-framework'
      fullPath: '/ai-governance-framework'
      preLoaderRoute: typeof AiGovernanceFrameworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar': {
      id: '/ar'
      path: '/ar'
      fullPath: '/ar'
      preLoaderRoute: typeof ArRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cs': {
      id: '/cs'
      path: '/cs'
      fullPath: '/cs'
      preLoaderRoute: typeof CsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/el': {
      id: '/el'
      path: '/el'
      fullPath: '/el'
      preLoaderRoute: typeof ElRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es': {
      id: '/es'
      path: '/es'
      fullPath: '/es'
      preLoaderRoute: typeof EsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr': {
      id: '/fr'
      path: '/fr'
      fullPath: '/fr'
      preLoaderRoute: typeof FrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/he': {
      id: '/he'
      path: '/he'
      fullPath: '/he'
      preLoaderRoute: typeof HeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it': {
      id: '/it'
      path: '/it'
      fullPath: '/it'
      preLoaderRoute: typeof ItRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ja': {
      id: '/ja'
      path: '/ja'
      fullPath: '/ja'
      preLoaderRoute: typeof JaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko': {
      id: '/ko'
      path: '/ko'
      fullPath: '/ko'
      preLoaderRoute: typeof KoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pt': {
      id: '/pt'
      path: '/pt'
      fullPath: '/pt'
      preLoaderRoute: typeof PtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru': {
      id: '/ru'
      path: '/ru'
      fullPath: '/ru'
      preLoaderRoute: typeof RuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sv': {
      id: '/sv'
      path: '/sv'
      fullPath: '/sv'
      preLoaderRoute: typeof SvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sw': {
      id: '/sw'
      path: '/sw'
      fullPath: '/sw'
      preLoaderRoute: typeof SwRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh': {
      id: '/zh'
      path: '/zh'
      fullPath: '/zh'
      preLoaderRoute: typeof ZhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiGovernanceFrameworkRoute: AiGovernanceFrameworkRoute,
  ArRoute: ArRoute,
  CsRoute: CsRoute,
  ElRoute: ElRoute,
  EsRoute: EsRoute,
  FrRoute: FrRoute,
  HeRoute: HeRoute,
  ItRoute: ItRoute,
  JaRoute: JaRoute,
  KoRoute: KoRoute,
  McpRoute: McpRoute,
  PtRoute: PtRoute,
  RuRoute: RuRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SvRoute: SvRoute,
  SwRoute: SwRoute,
  ZhRoute: ZhRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
